site_name: 'SQLBot 文档'
site_url: 'https://sqlbot.cn/docs'
site_description: 'SQLBot 是基于大模型和 RAG 的智能问数系统'
site_author: '飞致云'
repo_name: 'SQLBot'
repo_url: 'https://github.com/dataease/SQLBot'

use_directory_urls: false

edit_uri: https://github.com/dataease/SQLBot-Docs
theme:
    name: 'material'
    logo: 'img/logo-white.png'
    favicon: 'img/favicon.png'
    language: 'zh'
    highlightjs: true
    hljs_languages:
        - yaml
        - django
    palette:
        - scheme: default
          accent: teal
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
        - scheme: slate
          accent: teal
          toggle:
              icon: material/weather-night
              name: Switch to light mode
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.indexes
        - navigation.top
        - search.suggest
        - search.highlight
        - search.share
        - header.autohide
        - content.tabs.link
    custom_dir: "theme"
nav:
    - 产品介绍: index.md
    - 快速入门: quick_start.md
    - 更新日志: changelog.md
    - 系统架构: system_arch.md
    - 安装部署:
        - 离线安装（生产环境推荐）: installation/offline_installtion.md
        - 离线升级: installation/offline_upgrade.md        
        - 1Panel 安装: installation/1panel_installtion.md
        - 阿里云安装: installation/aliyun_installtion.md
        - 在线方式安装: installation/online_installtion.md
        - Windows 下安装: installation/windows_installation.md
        - 命令行工具: installation/cli.md
        - 源码运行: installation/source_run.md
        - 数据迁移: installation/migration.md
    - 功能手册:
        - 数据源:
            - 数据源概览: user_manual/datasource_description.md
            - 配置 Excel/CSV 数据: user_manual/datasource_excel.md
            - 配置 MySQL 数据源: user_manual/datasource_mysql.md
            - 配置 Oracle 数据源: user_manual/datasource_oracle.md
            - 配置 PostgreSQL 数据源: user_manual/datasource_postgresql.md
            - 配置 SQL Server 数据源: user_manual/datasource_sqlserver.md
            - 配置 ClickHouse 数据源: user_manual/datasource_clickhouse.md
            - 配置 达梦 数据源: user_manual/datasource_DM.md
            - 配置 Doris 数据源: user_manual/datasource_Doris.md
            - 配置 AWS Redshift 数据源: user_manual/datasource_redshift.md
            - 配置 Elasticsearch 数据源: user_manual/datasource_elasticsearch.md
            - 配置 Kingbase 数据源: user_manual/datasource_kingbase.md
            - 配置 StarRocks 数据源: user_manual/datasource_starrocks.md
        - 智能问数:  user_manual/smart_question_description.md
        - 仪表板: user_manual/dashboard_description.md
        - 小助手应用: user_manual/assistant.md
        - 设置:
            - 成员管理:  user_manual/member.md
            - 权限配置:  user_manual/permission.md
            - 术语配置:  user_manual/professional.md
            - SQL 示例库: user_manual/data_training.md
        - 系统管理:
            - 用户管理: system/user.md
            - 工作空间: system/workspace.md
            - AI 模型配置: system/model.md
            - 嵌入式管理: system/embedding.md
            - 系统设置:
                - 参数设置: system/parameter_setting.md
        - X-Pack:
            - 自定义提示词: X-Pack/prompt.md
            - 登录认证: X-Pack/identification_setting.md
            - 平台对接: X-Pack/platform_integration.md
            - 外观设置: X-Pack/appearance_configuration.md
            - 第三方平台设置: X-Pack/third-party-platform-settings.md
            - 操作日志: X-Pack/operation_log.md


    - 常见问题:
        - 安装部署: faq/installation.md
        - 数据源: faq/datasource.md
        - 智能问数: faq/smart_question_description.md
        - 小助手应用: faq/assistant.md
        - MCP: faq/mcp.md
        - 其他: faq/other.md
    - 模型接入:
        - Ollama 部署模型接入 SQLBot: model_integration/ollama.md
    - MCP 服务: mcp_server.md
    - DataEase 接入: dataease_integration.md
    - 嵌入式对接: embedding_integration.md
    - 最佳实践: best_practice.md
    - 商业版本: buy.md
    - 联系我们: contact.md
    
markdown_extensions:
    - admonition
    - codehilite:
          guess_lang: True
          linenums: False
    - toc:
          permalink: True
    - footnotes
    - attr_list
    - def_list
    - tables
    - abbr
    - md_in_html
    - pymdownx.extra
    - pymdownx.arithmatex
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
          emoji_generator: !!python/name:pymdownx.emoji.to_png
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde
    - pymdownx.betterem
    - pymdownx.progressbar
#    - lightgallery
    - pymdownx.tabbed:
        alternate_style: true

extra_css:
    - css/extra.css

copyright: Copyright &copy; 2014-2026 <a href="https://www.fit2cloud.com">杭州飞致云信息科技有限公司</a>, All Rights Reserved. <a href="http://www.beian.miit.gov.cn" target="_blank">浙ICP备14038283号-9</a>

plugins:
    - search:
          lang:
              - en
              - ja
          separator: '[\s\-\.]+'
extra:
    version:
      provider: mike
      warning: false
    analytics:
      provider: google
      property: G-9362Z0KNSP
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/dataease/SQLBot
      - icon: fontawesome/solid/envelope
        link: mailto:support@fit2cloud.com
      - icon: fontawesome/solid/phone
        link: tel://400-052-0755
